#' @export
#' @title clean_location_names
#' @name clean_location_names 
#' @description this function is used to clean the locations pulled from taxonomy database (used in clean_psql_data)
clean_location_names <- function(
    original_data
){
  # Rename original location name column ----
  original_data$original_location_name = original_data$location
  
  original_data$location=dplyr::case_when(
    #Kenya
    original_data$location=='AFR::KEN::KE-600::Bondo'~'AFR::KEN::Nyanza::Bondo',
    original_data$location=='AFR::KEN::KE-30'~'AFR::KEN::Nairobi::Nairobi',
    original_data$location=='AFR::KEN::KE-17::KodiagaGKPrison'~'AFR::KEN::Nyanza::Kisumu::KodiagaGKPrison',
    #Tanzania
    original_data$location=='AFR::TZA::TZ-01::Kati'~'AFR::TZA::Zanzibar::Unguja::Unguja',
    original_data$location=='AFR::TZA::TZ-01::Arumeru'~'AFR::TZA::Zanzibar::Unguja::Arumeru',
    original_data$location=='AFR::TZA::TZ-02::Kigamboni'~'AFR::TZA::Mainland::Dar es Salaam::Temeke::Kigamboni',
    original_data$location=='AFR::TZA::TZ-02::Ubungo'~'AFR::TZA::Mainland::Dar es Salaam::Kinondoni::Ubungo',
    #Cameroon
    original_data$location=='AFR::CMR::CM-AD'~'AFR::CMR::Adamaoua',
    original_data$location=='AFR::CMR::CM-CE'~'AFR::CMR::Centre',
    original_data$location=='AFR::CMR::CM-EN'~'AFR::CMR::Far North',
    original_data$location=='AFR::CMR::CM-ES'~'AFR::CMR::East',
    original_data$location=='AFR::CMR::CM-LT'~'AFR::CMR::Littoral',
    original_data$location=='AFR::CMR::CM-NO'~'AFR::CMR::North',
    original_data$location=='AFR::CMR::CM-NW'~'AFR::CMR::North-West',
    original_data$location=='AFR::CMR::CM-OU'~'AFR::CMR::West',
    original_data$location=='AFR::CMR::CM-SU'~'AFR::CMR::South',
    original_data$location=='AFR::CMR::CM-SW'~'AFR::CMR::South-West',
    #Burundi
    original_data$location=='AFR::BDI::BI-BL::Bugarama::Magara'~'AFR::BDI::Bujumbura Rural::Bugarama::Magara',
    original_data$location=='AFR::BDI::BI-BM::Centre'~'AFR::BDI::Bujumbura Mairie::Bujumbura Center Sanitary District',
    original_data$location=='AFR::BDI::BI-BM::Mukaza::Hospital Prince Regent Charles'~'AFR::BDI::Bujumbura Mairie::Buyenzi::Prince Regent Charles Hospital',
    original_data$location=='AFR::BDI::BI-BM::Nord'~'AFR::BDI::Bujumbura Mairie::Bujumbura North Sanitary District',
    original_data$location=='AFR::BDI::BI-BM::Sud'~'AFR::BDI::Bujumbura Mairie::Bujumbura South Sanitary District',
    original_data$location=='AFR::BDI::BI-BM|BI-CI'~'AFR::BDI::Bujumbura Mairie|Cibitoke',
    original_data$location=='AFR::BDI::BI-CA::Cankuzo|Cendajuru|Kigamba'~'AFR::BDI::Cankuzo::Cankuzo|Cendajuru|Kigamba',
    original_data$location=='AFR::BDI::BI-CA::Gisagara|Mishiha'~'AFR::BDI::Cankuzo::Gisagara|Mishiha',
    original_data$location=='AFR::BDI::BI-CI::Buganda::Nyamitanga'~'AFR::BDI::Cibitoke::Buganda::Nyamitanga',
    original_data$location=='AFR::BDI::BI-GI::Giheta|Gitega'~'AFR::BDI::Gitega::Giheta|Gitega',
    original_data$location=='AFR::BDI::BI-GI::Bukirasazi|Buraza|Itaba|Makebuko'~'AFR::BDI::Gitega::Bukirasazi|Buraza|Itaba|Makebuko',
    original_data$location=='AFR::BDI::BI-GI::Gishubi|Nyanrusange|Ryansoro'~'AFR::BDI::Gitega::Gishubi|Nyanrusange|Ryansoro',
    original_data$location=='AFR::BDI::BI-KI::Bugabira|Kirundo'~'AFR::BDI::Kirundo::Bugabira|Kirundo',
    original_data$location=='AFR::BDI::BI-KI::Bwambarangwe|Gitobe'~'AFR::BDI::Kirundo::Bwambarangwe|Gitobe',
    original_data$location=='AFR::BDI::BI-KI::Ntega|Vumbi'~'AFR::BDI::Kirundo::Ntega|Vumbi',
    original_data$location=='AFR::BDI::BI-KR::Gihogazi|Mutumba|Nyabikere|Shombo'~'AFR::BDI::Karuzi::Gihogazi|Mutumba|Nyabikere|Shombo',
    original_data$location=='AFR::BDI::BI-KR::Bugenyuzi|Buhiga|Gitaramuka'~'AFR::BDI::Karuzi::Bugenyuzi|Buhiga|Gitaramuka',
    original_data$location=='AFR::BDI::BI-KY::Kabarore|Kayanza|Muruta'~'AFR::BDI::Kayanza::Kabarore|Kayanza|Muruta',
    original_data$location=='AFR::BDI::BI-KY::Gahombo|Gatara|Muhanga'~'AFR::BDI::Kayanza::Gahombo|Gatara|Muhanga',
    original_data$location=='AFR::BDI::BI-MU::Kiganda|Mbuye|Rutegama'~'AFR::BDI::Muramvya::Kiganda|Mbuye|Rutegama',
    original_data$location=='AFR::BDI::BI-MU::Bukeye|Muramvya'~'AFR::BDI::Muramvya::Bukeye|Muramvya',
    original_data$location=='AFR::BDI::BI-BM|BI-CI'~'AFR::BDI::Bujumbura Mairie|Cibitoke',
    #CIV
    original_data$location=='AFR::CIV::CI-CM::Aboisso'~'AFR::CIV::Comoe::Sud-Comoe::Aboisso',
    original_data$location=='AFR::CIV::CI-CM::Adiake'~'AFR::CIV::Comoe::Sud-Comoe::Adiake',
    original_data$location=='AFR::CIV::CI-AB::YopougonEst'~'AFR::CIV::Abidjan::YopougonEst',
    original_data$location=='AFR::CIV::CI-AB::AboboEst'~'AFR::CIV::Abidjan::AboboEst',
    original_data$location=='AFR::CIV::CI-AB::AboboOuest'~'AFR::CIV::Abidjan::AboboOuest',
    original_data$location=='AFR::CIV::CI-AB::Anyama'~'AFR::CIV::Abidjan::Anyama',
    original_data$location=='AFR::CIV::CI-AB::Abobo::AboboEst'~'AFR::CIV::Abidjan::Abobo::AboboEst',
    original_data$location=='AFR::CIV::CI-AB::Abobo::AboboOuest'~'AFR::CIV::Abidjan::Abobo::AboboOuest',
    #Ethiopia
    original_data$location=='AFR::ETH::ET-AF'~'AFR::ETH::Afar',
    original_data$location=='AFR::ETH::ET-AA|ET-AF|ET-AM|ET-BE|ET-DD|ET-OR|ET-SN|ET-TI'~'AFR::ETH::Addis Ababa|Afar|Amhara|Benishangul-Gumuz|Dire Dawa|Oromia|SNNP|Tigray',
    original_data$location=='AFR::ETH::ET-AA'~'AFR::ETH::Addis Ababa',
    original_data$location=='AFR::ETH::ET-AF|ET-AM|ET-BE|ET-OR|ET-SN|ET-SO|ET-TI'~'AFR::ETH::Afar|Amhara|Benishangul-Gumuz|Oromia|SNNP|Somali|Tigray',
    original_data$location=='AFR::ETH::ET-AF|ET-AM|ET-OR|ET-SN|ET-SO|ET-TI'~'AFR::ETH::Afar|Amhara|Oromia|SNNP|Somali|Tigray',
    original_data$location=='AFR::ETH::ET-AF|ET-AM|ET-OR|ET-SO'~'AFR::ETH::Afar|Amhara|Oromia|Somali',
    original_data$location=='ET-AF|ET-DD|ET-OR|ET-SO|ET-TI'~'AFR::ETH::Afar|Dire Dawa|Oromia|Somali|Tigray',
    original_data$location=='AFR::ETH::ET-AM::North Gonder'~'AFR::ETH::Amhara::North Gondar',
    original_data$location=='AFR::ETH::ET-AM::West Gojam'~'AFR::ETH::Amhara::West Gojam',
    original_data$location=='AFR::ETH::ET-AM'~'AFR::ETH::Amhara',
    original_data$location=='AFR::ETH::ET-AM|ET-BE|ET-DD|ET-SO'~'AFR::ETH::Amhara|Benishangul-Gumuz|Dire Dawa|Somali',
    original_data$location=='AFR::ETH::ET-AM|ET-OR|ET-SO'~'AFR::ETH::Amhara|Oromia|Somali',
    original_data$location=='AFR::ETH::ET-BE'~'AFR::ETH::Benishangul-Gumuz',
    original_data$location=='AFR::ETH::ET-DD'~'AFR::ETH::Dire Dawa',
    original_data$location=='AFR::ETH::ET-DD|ET-OR|ET-SO|ET-TI'~'AFR::ETH::Dire Dawa|Oromia|Somali|Tigray',
    original_data$location=='AFR::ETH::ET-DD|ET-SO|ET-TI'~'AFR::ETH::Dire Dawa|Somali|Tigray',
    original_data$location=='AFR::ETH::ET-HA'~'AFR::ETH::Harari',
    original_data$location=='AFR::ETH::ET-OR::Bale'~'AFR::ETH::Oromia::Bale',
    original_data$location=='AFR::ETH::ET-OR::Borena|Borena|Borena|Guji::Abaya|Gelana|MelkaSoda|Wadera'~'AFR::ETH::Oromia::Borena|Borena|Borena|Guji::Abaya|Gelana|Melka Soda|Wadera',
    original_data$location=='AFR::ETH::ET-OR::Borena|Borena|Borena|Borena|Guji::Abaya|Arero|Gelana|MelkaSoda|Wadera'~'AFR::ETH::Oromia::Borena|Borena|Borena|Borena|Guji::Abaya|Arero|Gelana|Melka Soda|Wadera',
    original_data$location=='AFR::ETH::ET-OR::Borena::Abaya|Gelana'~'AFR::ETH::Oromia::Borena|Borena::Abaya|Gelana',
    original_data$location=='AFR::ETH::ET-OR'~'AFR::ETH::Oromia',
    original_data$location=='AFR::ETH::ET-OR|ET-SO'~'AFR::ETH::Oromia|Somali',
    original_data$location=='AFR::ETH::ET-SN'~'AFR::ETH::SNNP',
    original_data$location=='AFR::ETH::ET-SO'~'AFR::ETH::Somali',
    original_data$location=='AFR::ETH::ET-TI'~'AFR::ETH::Tigray',
    original_data$location=='AFR::ETH::Harari::Harari'~'AFR::ETH::Harari',
    #Mozambique
    original_data$location=='AFR::MOZ::Maputo City'~'AFR::MOZ::Maputo::Maputo',
    #Malawi
    original_data$location=='AFR::MWI::MW-BL::ChilekaSeventhDayAdventist'~'AFR::MWI::Southern::Blantyre::ChilekaSeventhDayAdventist',
    original_data$location=='AFR::MWI::MW-BL::Limbe'~'AFR::MWI::Southern::Blantyre::Limbe',
    original_data$location=='AFR::MWI::MW-BL::Ndirande'~'AFR::MWI::Southern::Blantyre::Ndirande',
    original_data$location=='AFR::MWI::MW-BL::SocheMaternity'~'AFR::MWI::Southern::Blantyre::SocheMaternity',
    
    #Locations with changing parents and temporally overlapping observations
    original_data$location=='AFR::SSD::Western Nile::Fashoda'~'AFR::SSD::Fashoda::Fashoda County',
    original_data$location=='AFR::SSD::Eastern Bieh::Nyirol'~'AFR::SSD::Bieh::Nyirol',
    original_data$location=='AFR::SSD::Eastern Nile::Malakal'~'AFR::SSD::Central Upper Nile::Malakal',
    original_data$location=='AFR::SSD::Namorunyang::Kapoeta South'~'AFR::SSD::Kapoeta::Kapoeta South',
    original_data$location=='AFR::SSD::Yei River::Kajo-keji'~'AFR::SSD::SS-EC::Kajo-keji',
    original_data$location=='AFR::SSD::Namorunyang::Budi'~'AFR::SSD::Kapoeta::Budi',
    original_data$location=='AFR::SSD::Namorunyang::Kapoeta East'~'AFR::SSD::Kapoeta::Kapoeta East',
    original_data$location=='AFR::COD::Katanga::Kampemba Health District' ~ 'AFR::COD::Katanga::Kapemba Health District',
    original_data$location=='AFR::COD::Orientale::Nia Nia Health District' ~ 'AFR::COD::Orientale::Niania Health District',
    original_data$location=='AFR::COD::Equateur::Bolonge Health District' ~ 'AFR::COD::Equateur::Bolenge Health District',
    original_data$location=='AFR::COD::Equateur::Mankanza Health District' ~ 'AFR::COD::Equateur::Makanza Health District',
    
    
    
    TRUE ~ as.character(original_data$location)
  )

  ## restructure the composite locations
  original_data <- original_data %>% dplyr::rowwise()

  original_data$location=gsub('\\(|\\)','',original_data$location)
  original_data <- original_data %>%
    dplyr::ungroup() %>%
    tidyr::separate_wider_delim( 
      cols = location, 
      delim = "::", 
      names = c("who_region", "country", "admin1", "admin2", "admin3", "admin4", "admin5", "admin6"),
      too_few = "align_start",
      too_many = "error",
      cols_remove = FALSE) 

  original_data$admin1=dplyr::case_when(
    #Angola
    original_data$admin1=='AO-CNN'~'Cunene',
    original_data$admin1=='AO-HUI'~'Huila',
    original_data$admin1=='AO-UIG'~'Uige',
    original_data$admin1=='AO-BGU'~'Benguela',
    original_data$admin1=='AO-CNO'~'Cuanza Norte',
    original_data$admin1=='AO-CUS'~'Cuanza Sul',
    original_data$admin1=='AO-LNO'~'Lunda Norte',
    original_data$admin1=='AO-LUA'~'Luanda',
    original_data$admin1=='AO-MAL'~'Malanje',
    original_data$admin1=='AO-NAM'~'Namibe',
    original_data$admin1=='AO-ZAI'~'Zaire',
    original_data$admin1=='AO-BGO'~'Bengo',
    original_data$admin1=='AO-BIE'~'Bie',
    original_data$admin1=='AO-CAB'~'Cabinda',
    original_data$admin1=='AO-CCU'~'Kuando Kubango',
    original_data$admin1=='AO-HUA'~'Huambo',
    original_data$admin1=='AO-LSU'~'Lunda Sul',
    
    #BDI
    original_data$admin1=='BI-CA'~'Cankuzo',
    original_data$admin1=='BI-GI'~'Gitega',
    original_data$admin1=='BI-KI'~'Kirundo',
    original_data$admin1=='BI-KR'~'Karuzi',
    original_data$admin1=='BI-KI'~'Kirundo',
    original_data$admin1=='BI-KY'~'Kayanza',
    original_data$admin1=='BI-MU'~'Muramvya',
    
    #BEN
    original_data$admin1=='BJ-AK'~'Atacora',
    original_data$admin1=='BJ-AL'~'Alibori',
    original_data$admin1=='BJ-AQ'~'Atlantique',
    original_data$admin1=='BJ-AQ|BJ-LI'~'Atlantique|Littoral',
    original_data$admin1=='BJ-BO'~'Borgou',
    original_data$admin1=='BJ-CO'~'Collines',
    original_data$admin1=='BJ-DO'~'Donga',
    original_data$admin1=='BJ-KO'~'Couffo',
    original_data$admin1=='BJ-LI'~'Littoral',
    original_data$admin1=='BJ-MO'~'Mono',
    original_data$admin1=='BJ-OU'~'Oueme',
    original_data$admin1=='BJ-PL'~'Plateau',
    original_data$admin1=='BJ-ZO'~'Zou',
    original_data$admin1=='Atakora'~'Atacora',
    original_data$admin1=='Ouémé'~'Oueme',
    
    #BFA
    original_data$admin1=='BF-01'~'Boucle du Mouhoun',
    original_data$admin1=='BF-02'~'Cascades',
    original_data$admin1=='BF-03'~'Centre',
    original_data$admin1=='BF-04'~'Centre-Est',
    original_data$admin1=='BF-05'~'Centre-Nord',
    original_data$admin1=='BF-06'~'Centre-Ouest',
    original_data$admin1=='BF-07'~'Centre-Sud',
    original_data$admin1=='BF-08'~'Est',
    original_data$admin1=='BF-09'~'Hauts-Bassins',
    original_data$admin1=='BF-10'~'Nord',
    original_data$admin1=='BF-11'~'Plateau-Central',
    original_data$admin1=='BF-12'~'Sahel',
    original_data$admin1=='BF-13'~'Sud-Ouest',
    original_data$admin1=='BF-GNA'~'Gnagna',
    original_data$admin1=='BF-OUD'~'Oudalan',
    #CAF
    original_data$admin1=='CF-MP'~'Ombella-Mpoko',
    original_data$admin1=='CF-LB'~'Lobaye',
    original_data$admin1=='CF-BGF'~'Bangui',
    #CIV
    original_data$admin1=='CI-01'~'Lagunes',
    original_data$admin1=='CI-BS'~'Bas-Sassandra',
    original_data$admin1=='CI-CM'~'Comoe',
    original_data$admin1=='CI-DN'~'Denguele',
    original_data$admin1=='CI-GD'~'Goh-Djiboua',
    original_data$admin1=='CI-LC'~'Lacs',
    original_data$admin1=='CI-LG'~'Lagunes',
    original_data$admin1=='CI-MG'~'Montagnes',
    original_data$admin1=='CI-SM'~'Sassandra-Marahoue',
    original_data$admin1=='CI-SV'~'Savanes',
    original_data$admin1=='CI-VB'~'Vallee du Bandama',
    original_data$admin1=='CI-WR'~'Woroba',
    original_data$admin1=='CI-YM'~'Yamoussoukro',
    original_data$admin1=='CI-ZZ'~'Zanzan',
    #Algeria
    original_data$admin1=='DZ-09'~'Blida',
    original_data$admin1=='DZ-10'~'Bouira	',
    original_data$admin1=='DZ-16'~'Alger',
    original_data$admin1=='DZ-26'~'Medea',
    original_data$admin1=='DZ-42'~'Tipaza',
    original_data$admin1=='DZ-44'~'AinDefla	',
    original_data$admin1=='DZ-09|DZ-10|DZ-16|DZ-26|DZ-42|DZ-44'~'Blida|Bouira|Alger|Medea|Tipaza|AinDefla',
    #Ghana
    original_data$admin1=='GH-AH'~'Ashanti',
    original_data$admin1=='GH-CP'~'Central',
    original_data$admin1=='GH-EP'~'Eastern',
    original_data$admin1=='GH-AA'~'Greater Accra',
    original_data$admin1=='GH-UE'~'Upper East',
    original_data$admin1=='GH-TV'~'Volta',
    original_data$admin1=='GH-WP'~'Western',
    original_data$admin1=='GH-BA'~'Brong-Ahafo',
    original_data$admin1=='GH-NP'~'Northern',
    original_data$admin1=='GH-UW'~'Upper West',
    #Guinea
    original_data$admin1=='GN-B'~'Boke',
    original_data$admin1=='GN-C'~'Conakry',
    original_data$admin1=='GN-D'~'Kindia',
    original_data$admin1=='GN-F'~'Faranah',
    original_data$admin1=='GN-K'~'Kankan',
    original_data$admin1=='GN-L'~'Labe',
    original_data$admin1=='GN-M'~'Mamou',
    original_data$admin1=='GN-N'~'Nzerekore',
    original_data$admin1=="N'Zerekore"~'Nzerekore',
    
    #Guinea Bissau
    original_data$admin1=='GW-BM'~'Biombo',
    original_data$admin1=='GW-CA'~'Cacheu',
    original_data$admin1=='GW-OI'~'Oio',
    original_data$admin1=='GW-BS'~'Bissau',
    
    #MDG
    original_data$admin1=='MG-A'~'Toamasina',
    original_data$admin1=='MG-D'~'Antsiranana',
    original_data$admin1=='MG-F'~'Fianarantsoa',
    original_data$admin1=='MG-M'~'Mahajanga',
    original_data$admin1=='MG-T'~'Antananarivo',
    original_data$admin1=='MG-U'~'Toliara',
    original_data$admin1=='Referral Centers Hospital Monja Jaona'~'Fianarantsoa::Ambovombe::Referral Centers Hospital Monja Jaona',
    #Mali
    original_data$admin1=='ML-7'~'Gao',
    original_data$admin1=='ML-BKO'~'Bamako',
    original_data$admin1=='ML-1'~'Kayes',
    original_data$admin1=='ML-2'~'Koulikoro',
    original_data$admin1=='ML-5'~'Mopti',
    original_data$admin1=='ML-4'~'Segou',
    original_data$admin1=='ML-3'~'Sikasso',
    original_data$admin1=='ML-6'~'Tombouctou',
    original_data$admin1=='ML-8'~'Kidal',
    original_data$admin1=='ML-9'~'Menaka',
    #MRT
    original_data$admin1=='MR-04'~'Gorgol',
    #Malawi
    original_data$admin1=='MW-C'~'Central',
    original_data$admin1=='MW-N'~'Northern',
    original_data$admin1=='MW-S'~'Southern',
    original_data$admin1=='MW-DE'~'Central::Dedza',
    original_data$admin1=='MW-CK'~'Southern::Chikwawa',
    original_data$admin1=='MW-NS'~'Southern::Nsanje',
    original_data$admin1=='MW-PH'~'Southern::Phalombe',
    original_data$admin1=='MW-MH'~'Southern::Machinga',
    original_data$admin1=='MW-MU'~'Southern::Mulanje',
    #Niger
    original_data$admin1=='NE-6'~'Tillaberi',
    original_data$admin1=='NE-4'~'Maradi',
    original_data$admin1=='NE-2|NE-4|NE-5|NE-7'~'Diffa|Maradi|Tahoua|Zinder',
    original_data$admin1=='NE-2|NE-4|NE-6|NE-7'~'Diffa|Maradi|Tillaberi|Zinder',
    original_data$admin1=='NE-3|NE-4|NE-8'~'Dosso|Maradi|Niamey',
    original_data$admin1=='NE-3|NE-4|NE-5|NE-7'~'Dosso|Maradi|Tahoua|Zinder',
    original_data$admin1=='NE-5|NE-6'~'Tahoua|Tillaberi',
    #SLE
    original_data$admin1=='SL-E'~'Eastern',
    original_data$admin1=='SL-N'~'Northern',
    original_data$admin1=='SL-S'~'Southern',
    original_data$admin1=='SL-W'~'Western Area',
    #Sudan
    original_data$admin1=='SD-DN'~'North Darfur',
    original_data$admin1=='SD-DS'~'South Darfur',
    original_data$admin1=='SD-DW'~'West Darfur',
    original_data$admin1=='SD-GD'~'Gedaref',
    original_data$admin1=='SD-GZ'~'Gezira',
    original_data$admin1=='SD-KA'~'Kassala',
    original_data$admin1=='SD-KH'~'Khartoum',
    original_data$admin1=='SD-KN'~'North Kordofan',
    original_data$admin1=='SD-KS'~'South Kordofan',
    original_data$admin1=='SD-NB'~'Blue Nile',
    original_data$admin1=='SD-NO'~'Northern',
    original_data$admin1=='SD-NR'~'River Nile',
    original_data$admin1=='SD-NW'~'White Nile',
    original_data$admin1=='SD-RS'~'Red Sea',
    original_data$admin1=='SD-SI'~'Sennar',
    original_data$admin1=='SD-GD|SD-GZ|SD-KA|SD-KH|SD-NB|SD-NR|SD-RS'~'Gedaref|Gezira|Kassala|Khartoum|Blue Nile|River Nile|Red Sea',
    original_data$admin1=='SD-KH|SD-NB|SD-SI'~'Khartoum|Blue Nile|Sennar',
    #Somalia
    original_data$admin1=='SO-BN'~'Banaadir',
    original_data$admin1=='SO-GA'~'Galguduud',
    original_data$admin1=='SO-HI'~'Hiiraan',
    original_data$admin1=='SO-SD'~'Shabeellaha Dhexe',
    original_data$admin1=='SO-JH'~'Lower Juba',
    original_data$admin1=='SO-SH'~'Lower Shabelle',
    original_data$admin1=='SO-GA'~'Galguduud',
    original_data$admin1=='SO-BN|SO-GA|SO-HI|SO-SD'~'Banaadir|Galguduud|Hiiraan|Shabeellaha Dhexe',
    original_data$admin1=='SO-BN|SO-HI|SO-JH|SO-SH'~'Banaadir|Hiiraan|Lower Juba|Lower Shabelle',
    original_data$admin1=='SO-GE'~'Gedo',
    original_data$admin1=='SO-JD'~'Jubbada Dhexe',
    #South Sudan
    original_data$admin1=='SS-BW'~'Western Bahr el Ghazal',
    original_data$admin1=='SS-EC'~'Central Equatoria',
    original_data$admin1=='SS-EC|SS-EE'~'Central Equatoria|Eastern Equatoria',
    original_data$admin1=='SS-EC|SS-EE|SS-EW|SS-JG|SS-LK'~'Central Equatoria|Eastern Equatoria|Western Equatoria|Jonglei|Lakes',
    original_data$admin1=='SS-EC|SS-EE|SS-JG'~'Central Equatoria|Eastern Equatoria|Jonglei',
    original_data$admin1=='SS-EE'~'Eastern Equatoria',
    original_data$admin1=='SS-EW'~'Western Equatoria',
    original_data$admin1=='SS-JG'~'Jonglei',
    original_data$admin1=='SS-LK'~'Lakes',
    original_data$admin1=='SS-NU'~'Upper Nile',
    original_data$admin1=='SS-UY'~'Unity',
    original_data$admin1=='SS-WR'~'Warrap',
    #Tanzaina
    original_data$admin1=='TZ-02|TZ-07|TZ-11|TZ-15'~'Mainland|Zanzibar|Zanzibar::Dar es Salaam|Unguja|Unguja|Unguja::|Unguja North|Unguja South|Unguja West',
    original_data$admin1=='TZ-01'~'Mainland::Arusha',
    original_data$admin1=='TZ-02'~'Mainland::Dar es Salaam',
    original_data$admin1=='TZ-04'~'Mainland::Iringa',
    original_data$admin1=='TZ-05'~'Mainland::Kagera',
    original_data$admin1=='TZ-06'~'Zanzibar::Pemba::Pemba North',
    original_data$admin1=='TZ-07'~'Zanzibar::Unguja::Unguja North',
    original_data$admin1=='TZ-08'~'Mainland::Kigoma',
    original_data$admin1=='TZ-10'~'Zanzibar::Pemba::Pemba South',
    original_data$admin1=='TZ-14'~'Mainland::Mbeya',
    original_data$admin1=='TZ-15'~'Zanzibar::Unguja::Urban West',
    original_data$admin1=='TZ-16'~'Mainland::Morogoro',
    original_data$admin1=='TZ-17'~'Mainland::Mtwara',
    original_data$admin1=='TZ-18'~'Mainland::Mwanza',
    original_data$admin1=='TZ-19'~'Mainland::Pwani',
    original_data$admin1=='TZ-20'~'Mainland::Rukwa',
    original_data$admin1=='TZ-21'~'Mainland::Ruvuma',
    original_data$admin1=='TZ-22'~'Mainland::Shinyanga',
    original_data$admin1=='TZ-23'~'Mainland::Singida',
    original_data$admin1=='TZ-24'~'Mainland::Tabora',
    original_data$admin1=='TZ-25'~'Mainland::Tanga',
    original_data$admin1=='TZ-28'~'Mainland::Katavi',
    original_data$admin1=='TZ-29'~'Mainland::Njombe',
    original_data$admin1=='TZ-31'~'Mainland::Songwe',
    
    #Togo
    original_data$admin1=='TG-M'~'Maritime',
    
    #Uganda
    original_data$admin1=='UG-101'~'Kalangala',
    original_data$admin1=='UG-102'~'Kampala',
    original_data$admin1=='UG-103'~'Kiboga',
    original_data$admin1=='UG-104'~'Luwero',
    original_data$admin1=='UG-105'~'Masaka',
    original_data$admin1=='UG-106'~'Mpigi',
    original_data$admin1=='UG-107'~'Mubende',
    original_data$admin1=='UG-108'~'Mukono',
    original_data$admin1=='UG-109'~'Nakasongola',
    original_data$admin1=='UG-110'~'Rakai',
    original_data$admin1=='UG-111'~'Sembabule',
    original_data$admin1=='UG-112'~'Kayunga',
    original_data$admin1=='UG-113'~'Wakiso',
    original_data$admin1=='UG-114'~'Lyantonde',
    original_data$admin1=='UG-116'~'Nakaseke',
    original_data$admin1=='UG-117'~'Buikwe',
    original_data$admin1=='UG-118'~'Bukomansibi',
    original_data$admin1=='UG-119'~'Butambala',
    original_data$admin1=='UG-120'~'Buvuma',
    original_data$admin1=='UG-121'~'Gomba',
    original_data$admin1=='UG-122'~'Kalungu',
    original_data$admin1=='UG-123'~'Kyankwanzi',
    original_data$admin1=='UG-124'~'Lwengo',
    original_data$admin1=='UG-201'~'Bugiri',
    original_data$admin1=='UG-202'~'Busia',
    original_data$admin1=='UG-203'~'Iganga',
    original_data$admin1=='UG-204'~'Jinja',
    original_data$admin1=='UG-205'~'Kamuli',
    original_data$admin1=='UG-206'~'Kapchorwa',
    original_data$admin1=='UG-207'~'Katakwi',
    original_data$admin1=='UG-208'~'Kumi',
    original_data$admin1=='UG-210'~'Pallisa',
    original_data$admin1=='UG-211'~'Soroti',
    original_data$admin1=='UG-213'~'Kaberamaido',
    original_data$admin1=='UG-214'~'Mayuge',
    original_data$admin1=='UG-216'~'Amuria',
    original_data$admin1=='UG-217'~'Budaka',
    original_data$admin1=='UG-220'~'Bukwa',
    original_data$admin1=='UG-222'~'Kaliro',
    original_data$admin1=='UG-224'~'Namutumba',
    original_data$admin1=='UG-225'~'Bulambuli',
    original_data$admin1=='UG-226'~'Buyende',
    original_data$admin1=='UG-227'~'Kibuku',
    original_data$admin1=='UG-228'~'Kween',
    original_data$admin1=='UG-229'~'Luuka',
    original_data$admin1=='UG-230'~'Namayingo',
    original_data$admin1=='UG-231'~'Ngora',
    original_data$admin1=='UG-232'~'Serere',
    original_data$admin1=='UG-301'~'Adjumani',
    original_data$admin1=='UG-302'~'Apac',
    original_data$admin1=='UG-304'~'Gulu',
    original_data$admin1=='UG-305'~'Kitgum',
    original_data$admin1=='UG-306'~'Kotido',
    original_data$admin1=='UG-307'~'Lira',
    original_data$admin1=='UG-308'~'Moroto',
    original_data$admin1=='UG-309'~'Moyo',
    original_data$admin1=='UG-312'~'Pader',
    original_data$admin1=='UG-313'~'Yumbe',
    original_data$admin1=='UG-314'~'Abim',
    original_data$admin1=='UG-315'~'Amolatar',
    original_data$admin1=='UG-317'~'Dokolo',
    original_data$admin1=='UG-318'~'Kaabong',
    original_data$admin1=='UG-321'~'Oyam',
    original_data$admin1=='UG-322'~'Agago',
    original_data$admin1=='UG-323'~'Alebtong',
    original_data$admin1=='UG-324'~'Amudat',
    original_data$admin1=='UG-325'~'Kole',
    original_data$admin1=='UG-326'~'Lamwo',
    original_data$admin1=='UG-327'~'Napak',
    original_data$admin1=='UG-402'~'Bushenyi',
    original_data$admin1=='UG-406'~'Kasese',
    original_data$admin1=='UG-415'~'Kyenjojo',
    original_data$admin1=='UG_223'~'Manafwa',
    #ZAF
    original_data$admin1=='ZA-GT'~'Gauteng',
    original_data$admin1=='ZA-LP'~'Limpopo',
    #Zambia
    original_data$admin1=='ZM-01'~'Western',
    original_data$admin1=='ZM-02'~'Central',
    original_data$admin1=='ZM-05'~'Northern',
    original_data$admin1=='ZM-07'~'Southern',
    original_data$admin1=='ZM-08'~'Copperbelt',
    original_data$admin1=='ZM-09'~'Lusaka',
    #Zimbabwe
    original_data$admin1=='ZW-BU'~'Bulawayo',
    original_data$admin1=='ZW-HA'~'Harare',
    original_data$admin1=='ZW-MA'~'Manicaland',
    original_data$admin1=='ZW-MC'~'Mashonaland Central',
    original_data$admin1=='ZW-ME'~'Mashonaland East',
    original_data$admin1=='ZW-MI'~'Midlands',
    original_data$admin1=='ZW-MN'~'Matabeleland North',
    original_data$admin1=='ZW-MS'~'Matabeleland South',
    original_data$admin1=='ZW-MV'~'Masvingo',
    original_data$admin1=='ZW-MW'~'Mashonaland West',
    TRUE ~ as.character(original_data$admin1))

  original_data$admin2=dplyr::case_when(
    original_data$admin2=='MW-BA'~'Balaka',
    original_data$admin2=='MW-BL'~'Blantyre',
    original_data$admin2=='MW-CK'~'Chikwawa',
    original_data$admin2=='MW-CR'~'Chiradzulu',
    original_data$admin2=='MW-CT'~'Chitipa',
    original_data$admin2=='MW-DE'~'Dedza',
    original_data$admin2=='MW-DO'~'Dowa',
    original_data$admin2=='MW-KS'~'Kasungu',
    original_data$admin2=='MW-LI'~'Lilongwe',
    original_data$admin2=='MW-MC'~'Mchinji',
    original_data$admin2=='MW-MG'~'Mangochi',
    original_data$admin2=='MW-MU'~'Mulanje',
    original_data$admin2=='MW-MW'~'Balaka',
    original_data$admin2=='MW-MZ'~'Blantyre',
    original_data$admin2=='MW-NB'~'Chikwawa',
    original_data$admin2=='MW-NE'~'Chiradzulu',
    original_data$admin2=='MW-NI'~'Mwanza',
    original_data$admin2=='MW-NK'~'Nkhotakota',
    original_data$admin2=='MW-NS'~'Nsanje',
    original_data$admin2=='MW-NU'~'Ntcheu',
    original_data$admin2=='MW-RU'~'Balaka',
    original_data$admin2=='MW-SA'~'Blantyre',
    original_data$admin2=='MW-TH'~'Chikwawa',
    #BFA
    original_data$admin2=='BF-BAL'~'Bale',
    original_data$admin2=='BF-BAM'~'Bam',
    original_data$admin2=='BF-BAN'~'Banwa',
    original_data$admin2=='BF-BAZ'~'Bazega',
    original_data$admin2=='BF-BGR'~'Bougouriba',
    original_data$admin2=='BF-BLG'~'Boulgou',
    original_data$admin2=='BF-BLK'~'Boulkiemde',
    original_data$admin2=='BF-COM'~'Comoe',
    original_data$admin2=='BF-GAN'~'Ganzourgou',
    original_data$admin2=='BF-GNA'~'Gnagna',
    original_data$admin2=='BF-GOU'~'Gourma',
    original_data$admin2=='BF-HOU'~'Houet',
    original_data$admin2=='BF-IOB'~'Ioba',
    original_data$admin2=='BF-KAD'~'Kadiogo',
    original_data$admin2=='BF-KEN'~'Kenedougou',
    original_data$admin2=='BF-KMD'~'Komondjari',
    original_data$admin2=='BF-KMP'~'Kompienga',
    original_data$admin2=='BF-KOP'~'Koulpelogo',
    original_data$admin2=='BF-KOS'~'Kossi',
    original_data$admin2=='BF-KOT'~'Kouritenga',
    original_data$admin2=='BF-KOW'~'Kourweogo',
    original_data$admin2=='BF-LER'~'Leraba',
    original_data$admin2=='BF-LOR'~'Loroum',
    original_data$admin2=='BF-MOU'~'Mouhoun',
    original_data$admin2=='BF-NAM'~'Namentenga',
    original_data$admin2=='BF-NAO'~'Nahouri',
    original_data$admin2=='BF-NAY'~'Nayala',
    original_data$admin2=='BF-NOU'~'Noumbiel',
    original_data$admin2=='BF-OUB'~'Oubritenga',
    original_data$admin2=='BF-OUD'~'Oudalan',
    original_data$admin2=='BF-PAS'~'Passore',
    original_data$admin2=='BF-PON'~'Poni',
    original_data$admin2=='BF-SEN'~'Seno',
    original_data$admin2=='BF-SIS'~'Sissili',
    original_data$admin2=='BF-SMT'~'Sanmatenga',
    original_data$admin2=='BF-SNG'~'Sanguie',
    original_data$admin2=='BF-SOM'~'Soum',
    original_data$admin2=='BF-SOR'~'Sourou',
    original_data$admin2=='BF-TAP'~'Tapoa',
    original_data$admin2=='BF-TUI'~'Tuy',
    original_data$admin2=='BF-YAG'~'Yagha',
    original_data$admin2=='BF-YAT'~'Yatenga',
    original_data$admin2=='BF-ZIR'~'Ziro',
    original_data$admin2=='BF-ZON'~'Zondoma',
    original_data$admin2=='BF-ZOU'~'Zoundweogo',
    
    #Somalia
    original_data$admin2=='Badhaadhe'~'Badhaadhe',
    
    #GIN
    original_data$admin2=="GN-FR"~'Fria',
    original_data$admin2=="GN-KE"~'Kerouane',
    original_data$admin2=="GN-BF"~'Boffa',
    original_data$admin2=="GN-FO"~'Forecariah',
    original_data$admin2=="GN-FA"~'Faranah',
    original_data$admin2=="GN-MM"~'Mamou',
    original_data$admin2=="GN-KD"~'Kindia',
    original_data$admin2=="GN-BK"~'Boke',
    original_data$admin2=="GN-KA"~'Kankan',
    
    TRUE ~ as.character(original_data$admin2)
  )

  # merge updated admX columns into a new location name column
  original_data <- original_data %>%
    dplyr::ungroup() %>%
    tidyr::unite("location", who_region:admin6, sep = "::", na.rm = TRUE, remove = FALSE)
  
  return(original_data)
}
